// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opinion/V1/opinion.proto

package opinion

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Opinion struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Asunto               string   `protobuf:"bytes,2,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Autor                string   `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opinion) Reset()         { *m = Opinion{} }
func (m *Opinion) String() string { return proto.CompactTextString(m) }
func (*Opinion) ProtoMessage()    {}
func (*Opinion) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{0}
}

func (m *Opinion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opinion.Unmarshal(m, b)
}
func (m *Opinion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opinion.Marshal(b, m, deterministic)
}
func (m *Opinion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opinion.Merge(m, src)
}
func (m *Opinion) XXX_Size() int {
	return xxx_messageInfo_Opinion.Size(m)
}
func (m *Opinion) XXX_DiscardUnknown() {
	xxx_messageInfo_Opinion.DiscardUnknown(m)
}

var xxx_messageInfo_Opinion proto.InternalMessageInfo

func (m *Opinion) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Opinion) GetAsunto() string {
	if m != nil {
		return m.Asunto
	}
	return ""
}

func (m *Opinion) GetAutor() string {
	if m != nil {
		return m.Autor
	}
	return ""
}

// -- Get Opinion Messages types
type GetOpinionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOpinionRequest) Reset()         { *m = GetOpinionRequest{} }
func (m *GetOpinionRequest) String() string { return proto.CompactTextString(m) }
func (*GetOpinionRequest) ProtoMessage()    {}
func (*GetOpinionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{1}
}

func (m *GetOpinionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpinionRequest.Unmarshal(m, b)
}
func (m *GetOpinionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpinionRequest.Marshal(b, m, deterministic)
}
func (m *GetOpinionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpinionRequest.Merge(m, src)
}
func (m *GetOpinionRequest) XXX_Size() int {
	return xxx_messageInfo_GetOpinionRequest.Size(m)
}
func (m *GetOpinionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpinionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpinionRequest proto.InternalMessageInfo

func (m *GetOpinionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOpinionResponse struct {
	Opinion              *Opinion `protobuf:"bytes,1,opt,name=opinion,proto3" json:"opinion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOpinionResponse) Reset()         { *m = GetOpinionResponse{} }
func (m *GetOpinionResponse) String() string { return proto.CompactTextString(m) }
func (*GetOpinionResponse) ProtoMessage()    {}
func (*GetOpinionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{2}
}

func (m *GetOpinionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpinionResponse.Unmarshal(m, b)
}
func (m *GetOpinionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpinionResponse.Marshal(b, m, deterministic)
}
func (m *GetOpinionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpinionResponse.Merge(m, src)
}
func (m *GetOpinionResponse) XXX_Size() int {
	return xxx_messageInfo_GetOpinionResponse.Size(m)
}
func (m *GetOpinionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpinionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpinionResponse proto.InternalMessageInfo

func (m *GetOpinionResponse) GetOpinion() *Opinion {
	if m != nil {
		return m.Opinion
	}
	return nil
}

// -- Post Opinion Message types
type PostOpinionRequest struct {
	Opinion              *Opinion `protobuf:"bytes,1,opt,name=opinion,proto3" json:"opinion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOpinionRequest) Reset()         { *m = PostOpinionRequest{} }
func (m *PostOpinionRequest) String() string { return proto.CompactTextString(m) }
func (*PostOpinionRequest) ProtoMessage()    {}
func (*PostOpinionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{3}
}

func (m *PostOpinionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOpinionRequest.Unmarshal(m, b)
}
func (m *PostOpinionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOpinionRequest.Marshal(b, m, deterministic)
}
func (m *PostOpinionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOpinionRequest.Merge(m, src)
}
func (m *PostOpinionRequest) XXX_Size() int {
	return xxx_messageInfo_PostOpinionRequest.Size(m)
}
func (m *PostOpinionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOpinionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostOpinionRequest proto.InternalMessageInfo

func (m *PostOpinionRequest) GetOpinion() *Opinion {
	if m != nil {
		return m.Opinion
	}
	return nil
}

type PostOpinionResponse struct {
	Opinion              *Opinion `protobuf:"bytes,1,opt,name=opinion,proto3" json:"opinion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOpinionResponse) Reset()         { *m = PostOpinionResponse{} }
func (m *PostOpinionResponse) String() string { return proto.CompactTextString(m) }
func (*PostOpinionResponse) ProtoMessage()    {}
func (*PostOpinionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{4}
}

func (m *PostOpinionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOpinionResponse.Unmarshal(m, b)
}
func (m *PostOpinionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOpinionResponse.Marshal(b, m, deterministic)
}
func (m *PostOpinionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOpinionResponse.Merge(m, src)
}
func (m *PostOpinionResponse) XXX_Size() int {
	return xxx_messageInfo_PostOpinionResponse.Size(m)
}
func (m *PostOpinionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOpinionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostOpinionResponse proto.InternalMessageInfo

func (m *PostOpinionResponse) GetOpinion() *Opinion {
	if m != nil {
		return m.Opinion
	}
	return nil
}

// -- Delete Opinion Message types
type DeleteOpinionRequest struct {
	Opinion              *Opinion `protobuf:"bytes,1,opt,name=opinion,proto3" json:"opinion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOpinionRequest) Reset()         { *m = DeleteOpinionRequest{} }
func (m *DeleteOpinionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOpinionRequest) ProtoMessage()    {}
func (*DeleteOpinionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{5}
}

func (m *DeleteOpinionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOpinionRequest.Unmarshal(m, b)
}
func (m *DeleteOpinionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOpinionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOpinionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOpinionRequest.Merge(m, src)
}
func (m *DeleteOpinionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOpinionRequest.Size(m)
}
func (m *DeleteOpinionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOpinionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOpinionRequest proto.InternalMessageInfo

func (m *DeleteOpinionRequest) GetOpinion() *Opinion {
	if m != nil {
		return m.Opinion
	}
	return nil
}

type DeleteOpinionResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOpinionResponse) Reset()         { *m = DeleteOpinionResponse{} }
func (m *DeleteOpinionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOpinionResponse) ProtoMessage()    {}
func (*DeleteOpinionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e78773aa03024be2, []int{6}
}

func (m *DeleteOpinionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOpinionResponse.Unmarshal(m, b)
}
func (m *DeleteOpinionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOpinionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOpinionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOpinionResponse.Merge(m, src)
}
func (m *DeleteOpinionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOpinionResponse.Size(m)
}
func (m *DeleteOpinionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOpinionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOpinionResponse proto.InternalMessageInfo

func (m *DeleteOpinionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Opinion)(nil), "opinion.Opinion")
	proto.RegisterType((*GetOpinionRequest)(nil), "opinion.GetOpinionRequest")
	proto.RegisterType((*GetOpinionResponse)(nil), "opinion.GetOpinionResponse")
	proto.RegisterType((*PostOpinionRequest)(nil), "opinion.PostOpinionRequest")
	proto.RegisterType((*PostOpinionResponse)(nil), "opinion.PostOpinionResponse")
	proto.RegisterType((*DeleteOpinionRequest)(nil), "opinion.DeleteOpinionRequest")
	proto.RegisterType((*DeleteOpinionResponse)(nil), "opinion.DeleteOpinionResponse")
}

func init() { proto.RegisterFile("opinion/V1/opinion.proto", fileDescriptor_e78773aa03024be2) }

var fileDescriptor_e78773aa03024be2 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4e, 0x83, 0x40,
	0x14, 0x85, 0x03, 0x46, 0x1a, 0x4f, 0xe3, 0xdf, 0xb5, 0x36, 0x04, 0x7f, 0x62, 0x70, 0x63, 0x5c,
	0x94, 0x58, 0x5f, 0xa0, 0x1a, 0x4d, 0x5d, 0xa9, 0xa9, 0x89, 0x7b, 0xb4, 0xb3, 0x98, 0xc4, 0x70,
	0x91, 0x19, 0x7c, 0x70, 0x9f, 0xc0, 0x04, 0x2e, 0xb4, 0x05, 0x5c, 0x68, 0x77, 0x73, 0xe6, 0x9e,
	0x7c, 0xf7, 0x70, 0x18, 0xf8, 0x9c, 0xea, 0x44, 0x73, 0x12, 0xbd, 0x5e, 0x45, 0x72, 0x1c, 0xa5,
	0x19, 0x5b, 0xa6, 0x9e, 0xc8, 0x70, 0x8a, 0xde, 0x53, 0x79, 0xa4, 0x1d, 0xb8, 0x7a, 0xee, 0x3b,
	0x67, 0xce, 0xc5, 0xd6, 0xcc, 0xd5, 0x73, 0x1a, 0xc2, 0x8b, 0x4d, 0x9e, 0x58, 0xf6, 0xdd, 0xe2,
	0x4e, 0x14, 0x0d, 0xb0, 0x19, 0xe7, 0x96, 0x33, 0x7f, 0xa3, 0xb8, 0x2e, 0x45, 0x78, 0x8e, 0xfd,
	0xa9, 0xb2, 0xc2, 0x9a, 0xa9, 0xcf, 0x5c, 0x19, 0xdb, 0x44, 0x86, 0x13, 0xd0, 0xb2, 0xc9, 0xa4,
	0x9c, 0x18, 0x45, 0x97, 0xa8, 0xe2, 0x14, 0xd6, 0xfe, 0x78, 0x6f, 0x54, 0xa5, 0xad, 0xac, 0x75,
	0xde, 0x09, 0xe8, 0x99, 0x4d, 0x73, 0xcf, 0x5f, 0x08, 0x37, 0x38, 0x58, 0x21, 0xfc, 0x23, 0xc4,
	0x2d, 0x06, 0x77, 0xea, 0x43, 0x59, 0xb5, 0x46, 0x8c, 0x08, 0x87, 0x0d, 0x86, 0x04, 0x19, 0xc2,
	0x33, 0x36, 0xb6, 0xb9, 0x91, 0xde, 0x44, 0x8d, 0xbf, 0x1d, 0xec, 0x8a, 0xf7, 0x45, 0x65, 0x5f,
	0xfa, 0x5d, 0x33, 0xdd, 0x03, 0x8b, 0x3e, 0x29, 0xa8, 0xb7, 0xb5, 0xfe, 0x44, 0x70, 0xd4, 0x39,
	0x93, 0x95, 0x0f, 0xe8, 0x2f, 0x55, 0x42, 0x0b, 0x6f, 0xbb, 0xea, 0xe0, 0xb8, 0x7b, 0x28, 0xa4,
	0x47, 0x6c, 0xaf, 0x7c, 0x15, 0x9d, 0xd4, 0xf6, 0xae, 0xc6, 0x82, 0xd3, 0xdf, 0xc6, 0x25, 0xef,
	0xcd, 0x2b, 0x9e, 0xeb, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xcc, 0xfd, 0x65, 0xca,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpinionServicioClient is the client API for OpinionServicio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpinionServicioClient interface {
	GetOpinion(ctx context.Context, in *GetOpinionRequest, opts ...grpc.CallOption) (*GetOpinionResponse, error)
	PostOpinion(ctx context.Context, in *PostOpinionRequest, opts ...grpc.CallOption) (*PostOpinionResponse, error)
	DeleteOpinion(ctx context.Context, in *DeleteOpinionRequest, opts ...grpc.CallOption) (*DeleteOpinionResponse, error)
}

type opinionServicioClient struct {
	cc *grpc.ClientConn
}

func NewOpinionServicioClient(cc *grpc.ClientConn) OpinionServicioClient {
	return &opinionServicioClient{cc}
}

func (c *opinionServicioClient) GetOpinion(ctx context.Context, in *GetOpinionRequest, opts ...grpc.CallOption) (*GetOpinionResponse, error) {
	out := new(GetOpinionResponse)
	err := c.cc.Invoke(ctx, "/opinion.OpinionServicio/GetOpinion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opinionServicioClient) PostOpinion(ctx context.Context, in *PostOpinionRequest, opts ...grpc.CallOption) (*PostOpinionResponse, error) {
	out := new(PostOpinionResponse)
	err := c.cc.Invoke(ctx, "/opinion.OpinionServicio/PostOpinion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opinionServicioClient) DeleteOpinion(ctx context.Context, in *DeleteOpinionRequest, opts ...grpc.CallOption) (*DeleteOpinionResponse, error) {
	out := new(DeleteOpinionResponse)
	err := c.cc.Invoke(ctx, "/opinion.OpinionServicio/DeleteOpinion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpinionServicioServer is the server API for OpinionServicio service.
type OpinionServicioServer interface {
	GetOpinion(context.Context, *GetOpinionRequest) (*GetOpinionResponse, error)
	PostOpinion(context.Context, *PostOpinionRequest) (*PostOpinionResponse, error)
	DeleteOpinion(context.Context, *DeleteOpinionRequest) (*DeleteOpinionResponse, error)
}

// UnimplementedOpinionServicioServer can be embedded to have forward compatible implementations.
type UnimplementedOpinionServicioServer struct {
}

func (*UnimplementedOpinionServicioServer) GetOpinion(ctx context.Context, req *GetOpinionRequest) (*GetOpinionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpinion not implemented")
}
func (*UnimplementedOpinionServicioServer) PostOpinion(ctx context.Context, req *PostOpinionRequest) (*PostOpinionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostOpinion not implemented")
}
func (*UnimplementedOpinionServicioServer) DeleteOpinion(ctx context.Context, req *DeleteOpinionRequest) (*DeleteOpinionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOpinion not implemented")
}

func RegisterOpinionServicioServer(s *grpc.Server, srv OpinionServicioServer) {
	s.RegisterService(&_OpinionServicio_serviceDesc, srv)
}

func _OpinionServicio_GetOpinion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpinionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpinionServicioServer).GetOpinion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opinion.OpinionServicio/GetOpinion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpinionServicioServer).GetOpinion(ctx, req.(*GetOpinionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpinionServicio_PostOpinion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostOpinionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpinionServicioServer).PostOpinion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opinion.OpinionServicio/PostOpinion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpinionServicioServer).PostOpinion(ctx, req.(*PostOpinionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpinionServicio_DeleteOpinion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOpinionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpinionServicioServer).DeleteOpinion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opinion.OpinionServicio/DeleteOpinion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpinionServicioServer).DeleteOpinion(ctx, req.(*DeleteOpinionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpinionServicio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opinion.OpinionServicio",
	HandlerType: (*OpinionServicioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOpinion",
			Handler:    _OpinionServicio_GetOpinion_Handler,
		},
		{
			MethodName: "PostOpinion",
			Handler:    _OpinionServicio_PostOpinion_Handler,
		},
		{
			MethodName: "DeleteOpinion",
			Handler:    _OpinionServicio_DeleteOpinion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opinion/V1/opinion.proto",
}
